### ISSUE TITLE
不兼容值为"FFF"的UA

### ISSUE THREAD

**Issue by UnspokenSpell** [GiraffeLe/GiwifiScript#2]
# 现象
如果修改脚本内的UA的值为"FFF"，那么执行时报错：
```shell
root@OpenWRT:~/Script/GiwifiScript# giwifi.sh 11451407210 myPassword 192.168.99.2
hex string is too short, padding with zero bytes to length
non-hex digit
invalid hex iv value
```
# 评论
如果脚本中的UA包含常见操作系统的名称，那么会导致被关小黑屋。

# 解决方案(临时)
把"Win"替换成"And"
```shell
UA="Mozilla/5.0 (Anddows NT 10.0; And64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.5.1.4 Safari/537.36"
```

**Comment by TwiceTry** [comment]
我没有giwifi环境，估计是请求头ua为fff的请求返回的html与平常的不一样，导致解析表单错误，进而传参错误导致加密部分发生异常。
如果可以，把myget中的log注释取消，让它输出。
不知道有没有更好的方式，可以直接在这里把log文件内容回复给我。
我有空看后就想法处理。

**Comment by GiraffeLe** [comment]
> 我没有giwifi环境，估计是请求头ua为fff的请求返回的html与平常的不一样，导致解析表单错误，进而传参错误导致加密部分发生异常。
> 如果可以，把myget中的log注释取消，让它输出。
> 不知道有没有更好的方式，可以直接在这里把log文件内容回复给我。
> 我有空看后就想法处理。

giwifi服务端如果获取到不正常的ua/无法正确解析（例如fff）会向客户端返回403。换成正常ua即可。
至于被关进小黑屋，个人推测很有可能是**没修改ttl值导致被giwifi网关检测到**。

**Comment by TwiceTry** [comment]
脚本配合这个插件[luci-app-nettask](https://github.com/lucikap/luci-app-nettask?tab=readme-ov-file)
减少重复请求。

**Comment by UnspokenSpell** [comment]
> 我没有giwifi环境，估计是请求头ua为fff的请求返回的html与平常的不一样，导致解析表单错误，进而传参错误导致加密部分发生异常。 如果可以，把myget中的log注释取消，让它输出。 不知道有没有更好的方式，可以直接在这里把log文件内容回复给我。 我有空看后就想法处理。

我做了3次实验，用了3种不同的UA，具体的UA值和日志在各个文件夹中。

[Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14686346/Log.zip)

**Comment by UnspokenSpell** [comment]
> > 我没有giwifi环境，估计是请求头ua为fff的请求返回的html与平常的不一样，导致解析表单错误，进而传参错误导致加密部分发生异常。
> > 如果可以，把myget中的log注释取消，让它输出。
> > 不知道有没有更好的方式，可以直接在这里把log文件内容回复给我。
> > 我有空看后就想法处理。
> 
> giwifi服务端如果获取到不正常的ua/无法正确解析（例如fff）会向客户端返回403。换成正常ua即可。
> 至于被关进小黑屋，个人推测很有可能是**没修改ttl值导致被giwifi网关检测到**。

我以前用浏览器的 数据包导出bash脚本 的时候，用的UA就是FFF，能正常认证。🤔

**Comment by TwiceTry** [comment]
> > > 我没有giwifi环境，估计是请求头ua为fff的请求返回的html与平常的不一样，导致解析表单错误，进而传参错误导致加密部分发生异常。
> > > 如果可以，把myget中的log注释取消，让它输出。
> > > 不知道有没有更好的方式，可以直接在这里把log文件内容回复给我。
> > > 我有空看后就想法处理。
> > 
> > 
> > giwifi服务端如果获取到不正常的ua/无法正确解析（例如fff）会向客户端返回403。换成正常ua即可。
> > 至于被关进小黑屋，个人推测很有可能是**没修改ttl值导致被giwifi网关检测到**。
> 
> 我以前用浏览器的 数据包导出bash脚本 的时候，用的UA就是FFF，能正常认证。🤔

那能不能把在浏览器更改UA为FFF时正常的请求导出成bash的文本复制过来，我参考一下

**Comment by UnspokenSpell** [comment]
我的意思：浏览器用普通UA请求，然后导出脚本，将脚本中的UA改为FFF。


猜你想看：UA为FFF时的请求、回复。


我今晚第一节有课，晚点给你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月21日(周四) 下午5:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GiraffeLe/GiwifiScript] 不兼容值为"FFF"的UA (Issue #2)




    
我没有giwifi环境，估计是请求头ua为fff的请求返回的html与平常的不一样，导致解析表单错误，进而传参错误导致加密部分发生异常。
 如果可以，把myget中的log注释取消，让它输出。
 不知道有没有更好的方式，可以直接在这里把log文件内容回复给我。
 我有空看后就想法处理。
  
giwifi服务端如果获取到不正常的ua/无法正确解析（例如fff）会向客户端返回403。换成正常ua即可。
 至于被关进小黑屋，个人推测很有可能是没修改ttl值导致被giwifi网关检测到。
  
我以前用浏览器的 数据包导出bash脚本 的时候，用的UA就是FFF，能正常认证。🤔
  
那能不能把在浏览器更改UA为FFF时正常的请求导出成bash的文本复制过来，我参考一下

**Comment by UnspokenSpell** [comment]
我又做了3次实验。
### 解释
文件夹名的末尾的数字，是编号， 用来区分不同请求。
Running.log是被运行的代码，来源是
```shell
bash -x giwifi.sh 手机号 密码 192.168.99.2  > ./Running.log 2>&1
```
### 发现
- FFF不一定无法认证。Shell脚本 和 PostMan 就是正面例子

[Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14696297/Log.zip)

**Comment by TwiceTry** [comment]
> 我又做了3次实验。
> 
> ### 解释
> 文件夹名的末尾的数字，是编号， 用来区分不同请求。 Running.log是被运行的代码，来源是
> 
> ```shell
> bash -x giwifi.sh 手机号 密码 192.168.99.2  > ./Running.log 2>&1
> ```
> 
> ### 发现
> * FFF不一定无法认证。Shell脚本 和 PostMan 就是正面例子
> 
> [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14696297/Log.zip)

我先看看，还没解决过这种检测问题，有空的话可以拉最新giwifi.sh 运行，旧版表单解析有问题

**Comment by UnspokenSpell** [comment]
> > 我又做了3次实验。
> > ### 解释
> > 文件夹名的末尾的数字，是编号， 用来区分不同请求。 Running.log是被运行的代码，来源是
> > ```shell
> > bash -x giwifi.sh 手机号 密码 192.168.99.2  > ./Running.log 2>&1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 发现
> > 
> > * FFF不一定无法认证。Shell脚本 和 PostMan 就是正面例子
> > 
> > [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14696297/Log.zip)
> 
> 我先看看，还没解决过这种检测问题，有空的话可以拉最新giwifi.sh 运行，旧版表单解析有问题

接下来我会高频关注更新
[Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14697047/Log.zip)

**Comment by TwiceTry** [comment]
> > > 我又做了3次实验。
> > > ### 解释
> > > 文件夹名的末尾的数字，是编号， 用来区分不同请求。 Running.log是被运行的代码，来源是
> > > ```shell
> > > bash -x giwifi.sh 手机号 密码 192.168.99.2  > ./Running.log 2>&1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 发现
> > > 
> > > * FFF不一定无法认证。Shell脚本 和 PostMan 就是正面例子
> > > 
> > > [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14696297/Log.zip)
> > 
> > 
> > 我先看看，还没解决过这种检测问题，有空的话可以拉最新giwifi.sh 运行，旧版表单解析有问题
> 
> 接下来我会高频关注更新 [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14697047/Log.zip)

我不在giwifi环境，没法测试，留个联系方式吧，这样方便我及时收到测试结果。

**Comment by UnspokenSpell** [comment]
> > > > 我又做了3次实验。
> > > > ### 解释
> > > > 文件夹名的末尾的数字，是编号， 用来区分不同请求。 Running.log是被运行的代码，来源是
> > > > ```shell
> > > > bash -x giwifi.sh 手机号 密码 192.168.99.2  > ./Running.log 2>&1
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### 发现
> > > > 
> > > > * FFF不一定无法认证。Shell脚本 和 PostMan 就是正面例子
> > > > 
> > > > [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14696297/Log.zip)
> > > 
> > > 
> > > 我先看看，还没解决过这种检测问题，有空的话可以拉最新giwifi.sh 运行，旧版表单解析有问题
> > 
> > 
> > 接下来我会高频关注更新 [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14697047/Log.zip)
> 
> 我不在giwifi环境，没法测试，留个联系方式吧，这样方便我及时收到测试结果。

QQ: 2964293436
Mail: cutemuselsyse@gmail.com

**Comment by TwiceTry** [comment]
> > > > > 我又做了3次实验。
> > > > > ### 解释
> > > > > 文件夹名的末尾的数字，是编号， 用来区分不同请求。 Running.log是被运行的代码，来源是
> > > > > ```shell
> > > > > bash -x giwifi.sh 手机号 密码 192.168.99.2  > ./Running.log 2>&1
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ### 发现
> > > > > 
> > > > > * FFF不一定无法认证。Shell脚本 和 PostMan 就是正面例子
> > > > > 
> > > > > [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14696297/Log.zip)
> > > > 
> > > > 
> > > > 我先看看，还没解决过这种检测问题，有空的话可以拉最新giwifi.sh 运行，旧版表单解析有问题
> > > 
> > > 
> > > 接下来我会高频关注更新 [Log.zip](https://github.com/GiraffeLe/GiwifiScript/files/14697047/Log.zip)
> > 
> > 
> > 我不在giwifi环境，没法测试，留个联系方式吧，这样方便我及时收到测试结果。
> 
> Telegram：https://t.me/tenbatu

我看了看请求头的区别，我在我的fork里代码添加了origin referer，你拉我fork里的代码运行试试。telegram不会用，因为我不在giwifi环境下，测是没法测，设置那几个请求头也不管用的话，我也是没办法了。

**Comment by UnspokenSpell** [comment]
当UA中缺少一些关键的值时，比如"Mozilla"，"AppleWebKit"，会导致认证服务器不返回内容。

所以这不是脚本的问题，而是Server的问题。

经过实验，可以正常响应的最短UA：`Mozilla/ AppleWebKit/`

**Comment by GiraffeLe** [comment]
> 当UA中缺少一些关键的值时，比如"Mozilla"，"AppleWebKit"，会导致认证服务器不返回内容。
> 
> 所以这不是脚本的问题，而是Server的问题。
> 
> 经过实验，可以正常响应的最短UA：`Mozilla/ AppleWebKit/`

幽默服务端
